# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in offline mode and will not check for updates online.
org.gradle.offline=false

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and hence the package is not important to uniquely
# identify the contained resources. By enabling the namespacing feature, it is possible to
# make libraries with identical package names coexist.
android.nonTransitiveRClass=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable non-transitive R classes.
android.useAndroidX=true

# Kotlin/Native suppresses some irrelevant library warnings
kotlin.native.suppressDeprecatedCompilerMessages=true
